FROM node:16-alpine

WORKDIR /app
COPY . .
RUN npm ci

ARG ARG_JC_MONGO_CONNECTION
ARG ARG_JC_JWT_SECRET
ARG ARG_JC_TOKEN_EXPIRY

ENV JC_MONGO_CONNECTION=$ARG_JC_MONGO_CONNECTION
ENV JC_JWT_SECRET=$ARG_JC_JWT_SECRET
ENV JC_TOKEN_EXPIRY=$ARG_JC_TOKEN_EXPIRY

RUN npm run build

CMD ["npm", "run", "start:prod"]

