export enum ErrorCode {
  EMAIL_REGISTERED = 'EMAIL_REGISTERED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  FIELD_REQUIRED = 'FIELD_REQUIRED',
  INVALID_FORMAT = 'INVALID_FORMAT',
  INVALID_VALUE = 'INVALID_VALUE',
  CANT_BE_EMPTY = 'CANT_BE_EMPTY',
}
